version: 2
registries:
  github:
    type: nuget-feed
    url: https://nuget.pkg.github.com/maersktech/index.json
    username: ${{ github.actor }}
    password: ${{ secrets.GH_PACKAGES_READ_TOKEN }}
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "nuget"
    directory: "/"
    registries: "*"
    schedule:
      interval: "daily"
