#
# https://github.com/aquasecurity/trivy-action#using-trivy-to-scan-your-git-repo
#
name: Trivy scan

on:
  workflow_dispatch:
  push:
    branches: main
  pull_request:
    branches: main
    types:
      - opened
      - synchronize

concurrency:
  group: trivy-repository-scan-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Trivy scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin
        shell: bash

      - name: Run Trivy vulnerability scanner in repo mode
        run: |
          trivy fs . \
            --ignore-unfixed \
            --format sarif \
            --exit-code 1 \
            --no-progress \
            --output trivy-results.sarif \
            --severity HIGH,CRITICAL
        shell: bash

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'
